import paramiko
HOST="<NAS_LAN_IP>"; PORT=22; USER="<NAS_SSH_USER>"; PW="<NAS_SSH_PASSWORD>"
ssh = paramiko.SSHClient(); ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(HOST, PORT, USER, PW, timeout=20)
def run(c):
    _,o,e = ssh.exec_command(c); return o.read().decode("utf-8","replace")+e.read().decode("utf-8","replace")
print("== 主 config.yaml 中 gemini-primary 组定义 ==")
print(run("grep -B 2 -A 15 'gemini-primary' /home/<NAS_SSH_USER>/mihomo/config.yaml | head -50"))
print("== gemini-config.yaml 节点 ==")
print(run("grep -E 'name:|fixed:|url:' /home/<NAS_SSH_USER>/mihomo/gemini-config.yaml | head -40"))
print("== gemini-config.yaml 完整 proxy 段数量 / 节点名 ==")
print(run("grep -c 'type:' /home/<NAS_SSH_USER>/mihomo/gemini-config.yaml; awk '/^- name:/{print $3}' /home/<NAS_SSH_USER>/mihomo/gemini-config.yaml | head -20"))
print("== fygo main PID 及其环境变量 proxy ==")
print(run("FYGO_PID=$(pgrep -f 'fygo-browser/app/vendor/runtime/usr/lib/chromium/chromium' | head -1); echo PID=$FYGO_PID; cat /proc/$FYGO_PID/environ 2>/dev/null | tr '\\0' '\\n' | grep -iE 'proxy|HTTP_PROXY' | head"))
print("== node ==")
print(run("ls -la /home/<NAS_SSH_USER>/.nvm/versions/node/v22.22.3/bin/node 2>/dev/null; /home/<NAS_SSH_USER>/.nvm/versions/node/v22.22.3/bin/node --version"))
print("== NAS node modules ==")
print(run("ls /home/<NAS_SSH_USER>/.nvm/versions/node/v22.22.3/lib/node_modules/ 2>/dev/null"))
print("== check ws module ==")
print(run("cd /home/<NAS_SSH_USER>/.nvm/versions/node/v22.22.3/lib/node_modules && node -e 'try{console.log(\"ws\",require.resolve(\"ws\"))}catch(e){console.log(\"NO_WS\",e.message)}' 2>&1"))
print("== check playwright ==")
print(run("cd /home/<NAS_SSH_USER>/.nvm/versions/node/v22.22.3/lib/node_modules && node -e 'try{console.log(require.resolve(\"playwright-core\"))}catch(e){console.log(\"NO_PLAYWRIGHT\")}' 2>&1"))
print("== NAS 上 /home/<NAS_SSH_USER> 内 node 脚本 ==")
print(run("ls /home/<NAS_SSH_USER>/*.js 2>/dev/null; ls /home/<NAS_SSH_USER>/skill* 2>/dev/null"))
ssh.close()
